parameters:
    ruian.seo.page.class: Ruian\SeoBundle\Services\PageService
    ruian.seo.page.helper.class: Ruian\SeoBundle\Helpers\PageHelper
    ruian.seo.page.twig.class: Ruian\SeoBundle\Extensions\PageTwig

services:
    ruian.seo.page:
        class: %ruian.seo.page.class%
        arguments: [%ruian.seo.title%, %ruian.seo.metas%, %ruian.seo.metas_http_equiv%]

    ruian.seo.page.helper:
        class: %ruian.seo.page.helper.class%
        arguments: [@templating, @ruian.seo.page, %ruian.seo.engine%]
        scope: request
        tags:
            - { name: templating.helper, alias: ruian.seo.page }
    # Helper Twig
    ruian.seo.page.twig:
        class: %ruian.seo.page.twig.class%
        arguments: [@ruian.seo.page, %ruian.seo.engine%]
        tags:
            - { name: twig.extension }